name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0

      - name: Lint
        run: inso lint spec "Basic Suite" --verbose --src insomnia.json

      - name: Run test suites
        run: inso run test "Basic Suite" --env UnitTest --ci --src insomnia.json